---
- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile: 
    dest:
      "/etc/apache2/sites-enabled/{{ http_conf }}"
    regexp:
      "(.)+DocumentRoot /var/www/html"
    line:
      "DocumentRoot /var/www/html/{{ http_host }}/public_html"

  notify:
    - restart apache

- name: Create a directory if it does not exist
  file:
    path: "/var/www/html/{{ http_host }}/public_html"
    state: directory
    mode: '0755'

#- name: Move Wordpress Files into http_host
 # command: "mv /var/www/wordpress/* /var/www/{{ http_host }}/ creates=/var/www/{{ http_host }}/"
  #command: "mv /var/www/wordpress/* /var/www/{{ http_host }}"
 # become: yes

# Synchronize two directories on one remote host.
- synchronize:
    src: /var/www/wordpress/
    dest: /var/www/html/{{ http_host }}/public_html
  delegate_to: "{{ inventory_hostname }}"

- name: Recursively remove directory
  file:
    path: "/var/www/wordpress"
    state: absent

# - name: Copy sample config file
#   command: "cp /var/www/html/{{ http_host }}/public_html/wp-config-sample.php /var/www/html/{{ http_host }}/public_html/wp-config.php creates=/var/www/{{ http_host }}/wp-config.php"
#   become: yes

- name: Set up Wordpress wp-config.php
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/html/{{ http_host }}/public_html/wp-config.php"
    

# - name: Update WordPress config file
#   lineinfile:
#     dest:
#       "/var/www/html/{{ http_host }}/public_html/wp-config.php"
#     regexp:
#       "{{ item.regexp }}"
#     line:
#       "{{ item.line }}"
#   with_items:
#     - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{wp_mysql_db}}' );"}
#     - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{wp_mysql_user}}' );"}
#     - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{wp_mysql_password}}' );"}
#   become: yes

  - name: Recursively change ownership of a directory
  file:
    path: "/var/www/html/{{ http_host }}/public_html"
    state: "directory"
    recurse: yes
    owner: "www-data"
    group: "www-data"